version: '3'
services:
  # SQL database
  postgres:
    image: postgres:9.6.0
    restart: always
    volumes:
      - ktor-chat-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ktor-chat-db

volumes:
  ktor-chat-data: